# Generated by Django 4.2.5 on 2023-09-28 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0004_bookrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.RenameField(
            model_name='bookrequest',
            old_name='requested_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='bookrequest',
            old_name='user',
            new_name='requester',
        ),
        migrations.RemoveField(
            model_name='bookrequest',
            name='decision_by_owner',
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('requested', 'Requested'), ('borrowed', 'Borrowed')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='chosen_recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chosen_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='pickup_location',
            field=models.CharField(default='tbilisi', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
