# Generated by Django 4.2.5 on 2023-09-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrequest',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
