# Generated by Django 4.2.5 on 2023-09-29 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_interest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
