# Generated by Django 4.2.5 on 2023-09-29 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_alter_book_options_book_borrowed_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinterest',
            options={'ordering': ['id']},
        ),
    ]
